theme: jekyll-theme-minimal
title: Fertilizer
description: AI for LeekWars
logo: https://media.senscritique.com/media/000007296895/240/Leek_Wars.png
show_downloads: false
google_analytics: UA-146204588-1
